### ISSUE TITLE
Uncaught TypeError: Cannot read property 'basename' of undefined

### ISSUE THREAD

**Issue by ali-gs** [mrohland/plantuml#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 8.1 Single Language
**Thrown From**: [plantuml](https://github.com/mrohland/plantuml) package, v0.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'basename' of undefined

```
At /C:/Users/Ali%20Imran/.atom/packages/plantuml/lib/file-utils.coffee:51

TypeError: Cannot read property 'basename' of undefined
  at Function.module.exports.FileUtil.getPngFilename (C:\Users\Ali Imran\.atom\packages\plantuml\lib\file-utils.coffee:35:20)
  at module.exports.FileUtil.getPngFilePath (C:\Users\Ali Imran\.atom\packages\plantuml\lib\file-utils.coffee:15:28)
  at Object.module.exports.Plantuml.generate (C:\Users\Ali Imran\.atom\packages\plantuml\lib\plantuml.coffee:25:23)
  at atom-workspace.subscriptions.add.atom.commands.add.plantuml:generate (C:\Users\Ali Imran\.atom\packages\plantuml\lib\plantuml.coffee:12:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\src\window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\src\window-event-handler.js:157:33)
  at HTMLDocument.handler (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Ali Imran\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```
### Commands

```
     -0:36 go-to-line:toggle (atom-text-editor.editor)
     -0:33.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:22.4.0 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
asciidoc-preview, v0.6.0
language-asciidoc, v0.12.0
language-plantuml, v0.1.1
language-textile, v0.2.0
plantuml, v0.1.2
plantuml-viewer, v0.6.1

# Dev
No dev packages
```

**Comment by togakangaroo** [comment]
Same thing with the following straight off the plantuml website

```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```

saved in abm.plantuml works fine when passed directly to plantuml
