### ISSUE TITLE
Uncaught TypeError: path.basename is not a function

### ISSUE THREAD

**Issue by jinke5245** [mrohland/plantuml#17]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [plantuml](https://github.com/mrohland/plantuml) package, v0.1.2
### Stack Trace

Uncaught TypeError: path.basename is not a function

```
At /Users/jinke/.atom/packages/plantuml/lib/file-utils.coffee:35

TypeError: path.basename is not a function
    at Function.module.exports.FileUtil.getPngFilename (/Users/jinke/.atom/packages/plantuml/lib/file-utils.coffee:35:21)
    at module.exports.FileUtil.getPngFilePath (/Users/jinke/.atom/packages/plantuml/lib/file-utils.coffee:15:28)
    at Object.module.exports.Plantuml.generate (/Users/jinke/.atom/packages/plantuml/lib/plantuml.coffee:25:23)
    at atom-workspace.subscriptions.add.atom.commands.add.plantuml:generate (/Users/jinke/.atom/packages/plantuml/lib/plantuml.coffee:12:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1010:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:30.7.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:27.6.0 grammar-selector:show (atom-text-editor.editor)
     -0:24.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17 core:paste (atom-text-editor.editor.is-focused)
     -0:05.5.0 plantuml:generate (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
language-plantuml, v0.2.0
plantuml, v0.1.2

# Dev
No dev packages
```

**Comment by jt3k** [comment]
+1

[Enter steps to reproduce below:]
1. start atom
2. write plantuml-code
3. run generate plantuml

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.5
**Thrown From**: [plantuml](https://github.com/mrohland/plantuml) package, v0.1.2

### Stack Trace

Uncaught TypeError: path.basename is not a function

```
At /Users/jt3k/.atom/packages/plantuml/lib/file-utils.coffee:35

TypeError: path.basename is not a function
    at Function.module.exports.FileUtil.getPngFilename (/Users/jt3k/.atom/packages/plantuml/lib/file-utils.coffee:35:21)
    at module.exports.FileUtil.getPngFilePath (/Users/jt3k/.atom/packages/plantuml/lib/file-utils.coffee:15:28)
    at Object.module.exports.Plantuml.generate (/Users/jt3k/.atom/packages/plantuml/lib/plantuml.coffee:25:23)
    at atom-workspace.subscriptions.add.atom.commands.add.plantuml:generate (/Users/jt3k/.atom/packages/plantuml/lib/plantuml.coffee:12:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
 13x -1:23.1.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -1:21 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:17.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:47.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:42 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:38.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:38.6.0 set-syntax:PlantUML (atom-text-editor.editor)
     -0:36.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:31.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:29.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:27.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:27.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:23.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:21.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:17.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17.8.0 plantuml:generate (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "packagesWithKeymapsDisabled": [
      "terminal-panel",
      "atom-terminal"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
activate-power-mode, v0.8.1 (active)
aesthetic-ui, v2.0.0 (inactive)
atom-beautify, v0.29.11 (inactive)
atom-like-brackets-editor, v1.1.4 (active)
atom-pair, v2.0.10 (active)
atom-ternjs, v0.15.0 (active)
auto-detect-indentation, v1.2.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.6.1 (active)
autocomplete-paths, v1.0.2 (active)
comment, v0.5.0 (inactive)
duplicate-line-or-selection, v0.5.0 (inactive)
emmet, v2.4.3 (active)
es6-javascript, v1.0.0 (inactive)
file-icons, v1.7.19 (active)
fold-functions, v0.4.4 (active)
fold-lines, v0.2.1 (active)
git-control, v0.8.2 (inactive)
git-plus, v5.16.2 (inactive)
git-status, v0.3.4 (inactive)
git-time-machine, v1.5.3 (inactive)
guess-indent, v0.1.0 (inactive)
highlight-bad-chars, v1.0.5 (active)
highlight-selected, v0.11.2 (active)
indent-detective, v0.1.0 (active)
indent-guide-improved, v1.4.9 (active)
indent-toggle-on-paste, v0.1.3 (inactive)
indent-tooltip, v0.2.0 (inactive)
jshint, v1.8.6 (active)
language-dot-template, v0.2.0 (active)
language-javascript-jsx, v0.3.7 (active)
language-mjml, v1.3.0 (active)
language-plantuml, v0.2.0 (active)
language-pug, v0.0.17 (active)
lines, v0.13.1 (inactive)
linter, v1.11.16 (active)
linter-eslint, v7.2.4 (active)
linter-jshint, v2.1.0 (active)
linter-markdown, v2.0.1 (active)
linter-pug-lint, v0.2.0 (active)
markdown-folder, v0.5.0 (inactive)
markdown-scroll-sync, v2.1.2 (active)
motepair, v0.21.0 (active)
npm-install, v4.0.3 (inactive)
npm-plus, v0.4.0 (inactive)
pigments, v0.34.0 (active)
plantuml, v0.1.2 (active)
plantuml-viewer, v0.7.0 (active)
platformio-ide-terminal, v2.2.0 (active)
project-manager, v2.9.7 (active)
react, v0.16.0 (active)
remember-folds, v0.2.0 (active)
set-syntax, v0.3.0 (active)
simple-drag-drop-text, v0.3.1 (active)
styles-highlighter, v2.3.0 (inactive)
Stylus, v3.0.0 (active)
stylus-autocompile, v0.6.1 (inactive)
sync-settings, v0.7.2 (active)
terminal-panel, v1.14.1 (active)
tool-bar-markdown-writer, v0.2.0 (active)
trailing-spaces, v0.3.2 (active)
turbo-javascript, v1.4.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
