### ISSUE TITLE
Object.require is deprecated.

### ISSUE THREAD

**Issue by zibo-wang** [mrohland/plantuml#19]
Use `remote.Dialog` instead of `remote.require("dialog")`
```
Object.require (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:57:12)
Object.<anonymous> (/Users/Roger/.dotfiles/atom/packages/plantuml/lib/file-utils.coffee:8:19)
Object.<anonymous> (/Users/Roger/.dotfiles/atom/packages/plantuml/lib/file-utils.coffee:64:4)
Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
Object..coffee (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
Module.load (module.js:473:32)
```

**Comment by caberham** [comment]
Not sure if this helps!

**Comment by whyvrafvr** [comment]
Got the same installing plantuml package on Atom and then I got an issue trying to generate a plantuml : 
TypeError: Cannot read property 'file' of undefined
    at module.exports.FileUtil.prepareFile (/Users/jsie/.atom/packages/plantuml/lib/file-utils.coffee:9:8)
    at Object.generate (/Users/jsie/.atom/packages/plantuml/lib/plantuml.coffee:23:18)
    at atom-workspace.subscriptions.add.atom.commands.add.plantuml:generate (/Users/jsie/.atom/packages/plantuml/lib/plantuml.coffee:12:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by iOrevir** [comment]
I have no error message and do not understand the implications of this issue.

**Comment by mxromero** [comment]
hi, when ejecute code of uml on atom show me two message of "deprecated calls" and the warning is (" Use remote.Dialog instead of remote.require("dialog")").
do you have any solution of this problem because i don't see the diagram.

**Comment by majacal** [comment]
i have the same issue
