### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by SpookySpoon** [mrohland/plantuml#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [plantuml](https://github.com/mrohland/plantuml) package 0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At C:\Users\Home-PC\.atom\packages\plantuml\lib\file-utils.coffee:9

TypeError: Cannot read property 'file' of undefined
    at module.exports.FileUtil.prepareFile (/packages/plantuml/lib/file-utils.coffee:9:8)
    at Object.generate (/packages/plantuml/lib/plantuml.coffee:23:18)
    at /packages/plantuml/lib/plantuml.coffee:12:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:14.7.0 plantuml:generate (atom-pane.pane.active)
```

### Non-Core Packages

```
plantuml 0.1.2 
```

**Comment by awhillas** [comment]
What does this mean? Can't find the plantuml.jar? Its defiantly on my path and I started atom from CLI...?

**Comment by biroeng** [comment]
/.atom/packages/plantuml/lib/file-utils.coffee:9
Hide Stack Trace
TypeError: Cannot read property 'file' of undefined
    at module.exports.FileUtil.prepareFile (/.atom/packages/plantuml/lib/file-utils.coffee:9:8)
    at Object.generate (/.atom/packages/plantuml/lib/plantuml.coffee:23:18)
    at HTMLElement.subscriptions.add.atom.commands.add.plantuml:generate (/.atom/packages/plantuml/lib/plantuml.coffee:12:32)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
